
GET http://localhost:5222/games

###
GET http://localhost:5222/games/3

###
POST http://localhost:5222/games
Content-Type: application/json

{
    "name" : "Super mario....more than 50 charators....",
    "genre" : "Platformer",
    "price" : 102.12,
    "releaseDate" : "2023-10-20"
}


###
PUT http://localhost:5222/games/3
Content-Type: application/json

{
    "name" : "xxxxxxxx",
    "genre" : "xxxxxxx",
    "price" : 99.99,
    "releaseDate" : "2023-10-20"
}


###
DELETE http://localhost:5222/games/10